import { useState } from "react";
import { useQuery, useMutation, type QueryClient } from "@tanstack/react-query";
import { formatRegimeName } from "@/lib/utils";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { 
  FileText, 
  RefreshCw, 
  Sparkles, 
  CheckCircle2, 
  XCircle, 
  AlertCircle,
  TrendingUp,
  Package
} from "lucide-react";
import { formatDistanceToNow } from "date-fns";

interface Rfq {
  id: string;
  rfqNumber: string;
  title: string;
  status: string;
  priority: string;
  requestedQuantity: number;
  unit: string;
  regimeAtGeneration: string;
  fdrAtGeneration: number;
  policySignal: string;
  isAutoGenerated: number;
  createdAt: string;
  materialId: string;
}

interface RfqOpportunity {
  materialId: string;
  materialCode: string;
  materialName: string;
  currentInventory: number;
  reorderPoint: number;
  recommendedOrderQuantity: number;
  regime: string;
  fdr: number;
  policySignal: string;
  priority: string;
  reason: string;
  urgencyScore: number;
}

export default function RfqDashboard() {
  const { toast } = useToast();
  const [selectedOpportunities, setSelectedOpportunities] = useState<Set<string>>(new Set());

  // Fetch all RFQs
  const { data: rfqs = [], isLoading: rfqsLoading, refetch: refetchRfqs } = useQuery<Rfq[]>({
    queryKey: ["/api/rfqs"],
  });

  // Fetch RFQ opportunities
  const { data: opportunities = [], isLoading: opportunitiesLoading, refetch: refetchOpportunities } = useQuery<RfqOpportunity[]>({
    queryKey: ["/api/rfqs/opportunities/scan"],
    enabled: false, // Only fetch on manual scan
  });

  // Auto-generate RFQs mutation
  const autoGenerateMutation = useMutation({
    mutationFn: async () => {
      return await apiRequest("POST", "/api/rfqs/generate", {});
    },
    onSuccess: (data) => {
      toast({
        title: "RFQs Generated",
        description: `Successfully generated ${data.generated} RFQs from ${data.total} opportunities.`,
      });
      queryClient.invalidateQueries({ queryKey: ["/api/rfqs"] });
      setSelectedOpportunities(new Set());
    },
    onError: (error: Error) => {
      toast({
        title: "Generation Failed",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  // Approve RFQ mutation
  const approveMutation = useMutation({
    mutationFn: async (rfqId: string) => {
      return await apiRequest("POST", `/api/rfqs/${rfqId}/approve`, {});
    },
    onSuccess: () => {
      toast({
        title: "RFQ Approved",
        description: "RFQ has been approved and sent to suppliers.",
      });
      queryClient.invalidateQueries({ queryKey: ["/api/rfqs"] });
    },
    onError: (error: Error) => {
      toast({
        title: "Approval Failed",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  // Delete RFQ mutation
  const deleteMutation = useMutation({
    mutationFn: async (rfqId: string) => {
      return await apiRequest("DELETE", `/api/rfqs/${rfqId}`);
    },
    onSuccess: () => {
      toast({
        title: "RFQ Deleted",
        description: "RFQ has been removed.",
      });
      queryClient.invalidateQueries({ queryKey: ["/api/rfqs"] });
    },
    onError: (error: Error) => {
      toast({
        title: "Delete Failed",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const getStatusBadge = (status: string) => {
    const variants: Record<string, { variant: any; label: string }> = {
      draft: { variant: "secondary", label: "Draft" },
      sent: { variant: "default", label: "Sent" },
      quotes_received: { variant: "default", label: "Quotes Received" },
      awarded: { variant: "default", label: "Awarded" },
      cancelled: { variant: "destructive", label: "Cancelled" },
    };
    const config = variants[status] || { variant: "secondary", label: status };
    return <Badge variant={config.variant as any} data-testid={`badge-status-${status}`}>{config.label}</Badge>;
  };

  const getPriorityBadge = (priority: string) => {
    const variants: Record<string, { variant: any; label: string }> = {
      urgent: { variant: "destructive", label: "Urgent" },
      high: { variant: "default", label: "High" },
      medium: { variant: "secondary", label: "Medium" },
      low: { variant: "outline", label: "Low" },
    };
    const config = variants[priority] || { variant: "secondary", label: priority };
    return <Badge variant={config.variant as any} data-testid={`badge-priority-${priority}`}>{config.label}</Badge>;
  };

  const getPolicySignalBadge = (signal: string) => {
    const variants: Record<string, { variant: any; label: string; icon: any }> = {
      buy_aggressively: { variant: "default", label: "Buy Aggressively", icon: TrendingUp },
      buy_moderately: { variant: "secondary", label: "Buy Moderately", icon: TrendingUp },
      buy_conservatively: { variant: "outline", label: "Buy Conservatively", icon: AlertCircle },
      wait_and_monitor: { variant: "destructive", label: "Wait & Monitor", icon: AlertCircle },
    };
    const config = variants[signal] || { variant: "secondary", label: signal, icon: AlertCircle };
    const Icon = config.icon;
    return (
      <Badge variant={config.variant as any} data-testid={`badge-signal-${signal}`}>
        <Icon className="w-3 h-3 mr-1" />
        {config.label}
      </Badge>
    );
  };

  return (
    <div className="flex flex-col gap-6 p-6">
      <div>
        <h1 className="text-3xl font-bold mb-2" data-testid="text-title">Automated RFQ Generation</h1>
        <p className="text-muted-foreground" data-testid="text-description">
          Monitor inventory levels and economic regime signals to automatically generate Request for Quotations
        </p>
      </div>

      {/* Action Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card data-testid="card-scan-opportunities">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Package className="w-5 h-5" />
              Scan for Opportunities
            </CardTitle>
            <CardDescription>
              Analyze inventory levels and identify materials below reorder point
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button 
              onClick={() => refetchOpportunities()} 
              disabled={opportunitiesLoading}
              className="w-full"
              data-testid="button-scan"
            >
              <RefreshCw className={`w-4 h-4 mr-2 ${opportunitiesLoading ? "animate-spin" : ""}`} />
              {opportunitiesLoading ? "Scanning..." : "Scan Inventory"}
            </Button>
          </CardContent>
        </Card>

        <Card data-testid="card-auto-generate">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="w-5 h-5" />
              Auto-Generate RFQs
            </CardTitle>
            <CardDescription>
              Automatically create RFQs for high priority materials
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button 
              onClick={() => autoGenerateMutation.mutate()} 
              disabled={autoGenerateMutation.isPending}
              className="w-full"
              variant="default"
              data-testid="button-generate"
            >
              <Sparkles className={`w-4 h-4 mr-2 ${autoGenerateMutation.isPending ? "animate-spin" : ""}`} />
              {autoGenerateMutation.isPending ? "Generating..." : "Generate RFQs"}
            </Button>
          </CardContent>
        </Card>
      </div>

      {/* Opportunities Table */}
      {opportunities.length > 0 && (
        <Card data-testid="card-opportunities">
          <CardHeader>
            <CardTitle>RFQ Opportunities ({opportunities.length})</CardTitle>
            <CardDescription>
              Materials below reorder point with regime-aware recommendations
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead data-testid="header-material">Material</TableHead>
                    <TableHead data-testid="header-inventory">Inventory</TableHead>
                    <TableHead data-testid="header-reorder">Reorder Point</TableHead>
                    <TableHead data-testid="header-recommended">Recommended Qty</TableHead>
                    <TableHead data-testid="header-regime">Regime Signal</TableHead>
                    <TableHead data-testid="header-priority">Priority</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {opportunities.map((opp) => (
                    <TableRow key={opp.materialId} data-testid={`row-opportunity-${opp.materialId}`}>
                      <TableCell data-testid={`cell-material-${opp.materialId}`}>
                        <div className="font-medium">{opp.materialName}</div>
                        <div className="text-sm text-muted-foreground">{opp.materialCode}</div>
                      </TableCell>
                      <TableCell data-testid={`cell-inventory-${opp.materialId}`}>
                        {opp.currentInventory.toFixed(1)}
                      </TableCell>
                      <TableCell data-testid={`cell-reorder-${opp.materialId}`}>
                        {opp.reorderPoint.toFixed(1)}
                      </TableCell>
                      <TableCell data-testid={`cell-recommended-${opp.materialId}`}>
                        {opp.recommendedOrderQuantity.toFixed(1)}
                      </TableCell>
                      <TableCell data-testid={`cell-signal-${opp.materialId}`}>
                        {getPolicySignalBadge(opp.policySignal)}
                        <div className="text-xs text-muted-foreground mt-1">
                          {formatRegimeName(opp.regime)} (FDR: {opp.fdr.toFixed(2)})
                        </div>
                      </TableCell>
                      <TableCell data-testid={`cell-priority-${opp.materialId}`}>
                        {getPriorityBadge(opp.priority)}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      )}

      {/* RFQs Table */}
      <Card data-testid="card-rfqs">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            Generated RFQs ({rfqs.length})
          </CardTitle>
          <CardDescription>
            All Request for Quotations with regime context
          </CardDescription>
        </CardHeader>
        <CardContent>
          {rfqsLoading ? (
            <div className="text-center py-8 text-muted-foreground" data-testid="text-loading">
              Loading RFQs...
            </div>
          ) : rfqs.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground" data-testid="text-no-rfqs">
              No RFQs generated yet. Click "Generate RFQs" to create automated requests.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead data-testid="header-rfq-number">RFQ #</TableHead>
                    <TableHead data-testid="header-title">Title</TableHead>
                    <TableHead data-testid="header-quantity">Quantity</TableHead>
                    <TableHead data-testid="header-status">Status</TableHead>
                    <TableHead data-testid="header-rfq-priority">Priority</TableHead>
                    <TableHead data-testid="header-regime-signal">Regime Signal</TableHead>
                    <TableHead data-testid="header-created">Created</TableHead>
                    <TableHead data-testid="header-actions">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {rfqs.map((rfq) => (
                    <TableRow key={rfq.id} data-testid={`row-rfq-${rfq.id}`}>
                      <TableCell data-testid={`cell-number-${rfq.id}`}>
                        <div className="font-medium">{rfq.rfqNumber}</div>
                        {rfq.isAutoGenerated === 1 && (
                          <Badge variant="outline" className="text-xs mt-1" data-testid={`badge-auto-${rfq.id}`}>
                            <Sparkles className="w-3 h-3 mr-1" />
                            Auto
                          </Badge>
                        )}
                      </TableCell>
                      <TableCell data-testid={`cell-title-${rfq.id}`}>{rfq.title}</TableCell>
                      <TableCell data-testid={`cell-qty-${rfq.id}`}>
                        {rfq.requestedQuantity.toFixed(1)} {rfq.unit}
                      </TableCell>
                      <TableCell data-testid={`cell-status-${rfq.id}`}>
                        {getStatusBadge(rfq.status)}
                      </TableCell>
                      <TableCell data-testid={`cell-priority-rfq-${rfq.id}`}>
                        {getPriorityBadge(rfq.priority)}
                      </TableCell>
                      <TableCell data-testid={`cell-signal-rfq-${rfq.id}`}>
                        {getPolicySignalBadge(rfq.policySignal)}
                        <div className="text-xs text-muted-foreground mt-1">
                          FDR: {rfq.fdrAtGeneration.toFixed(2)}
                        </div>
                      </TableCell>
                      <TableCell data-testid={`cell-created-${rfq.id}`}>
                        {formatDistanceToNow(new Date(rfq.createdAt), { addSuffix: true })}
                      </TableCell>
                      <TableCell data-testid={`cell-actions-${rfq.id}`}>
                        <div className="flex gap-2">
                          {rfq.status === "draft" && (
                            <Button
                              size="sm"
                              variant="default"
                              onClick={() => approveMutation.mutate(rfq.id)}
                              disabled={approveMutation.isPending}
                              data-testid={`button-approve-${rfq.id}`}
                            >
                              <CheckCircle2 className="w-4 h-4 mr-1" />
                              Approve
                            </Button>
                          )}
                          <Button
                            size="sm"
                            variant="destructive"
                            onClick={() => deleteMutation.mutate(rfq.id)}
                            disabled={deleteMutation.isPending}
                            data-testid={`button-delete-${rfq.id}`}
                          >
                            <XCircle className="w-4 h-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
