import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useLocation } from "wouter";
import {
  AlertTriangle,
  TrendingDown,
  TrendingUp,
  DollarSign,
  Target,
  Package,
  Activity,
  Maximize2,
  ArrowRight,
} from "lucide-react";

interface Signal {
  type: string;      // "procurement", "inventory", "production"
  action: string;    // "COUNTER_CYCLICAL_BUY", "REDUCE_INVENTORY", etc.
  description: string;
}

interface PolicySignalsProps {
  signals: Signal[];
}

interface SignalUx {
  label: string;
  icon: any;
  color: string;
  why: string;
  cta: string;
  to: string;
}

// Each signal carries its own "why" + "what to do" — never just a label.
const signalConfig: Record<string, SignalUx> = {
  // Procurement actions
  "procurement:normal": {
    label: "Standard Procurement",
    icon: Target,
    color: "text-blue-600",
    why: "Macro signals are balanced. Run normal cadence and re-check expiring contracts.",
    cta: "Review procurement",
    to: "/procurement",
  },
  "procurement:strategic_buy": {
    label: "Strategic Purchasing",
    icon: TrendingUp,
    color: "text-emerald-600",
    why: "Regime favors locking in supplier terms before input costs accelerate.",
    cta: "Issue RFQs",
    to: "/rfq-generation",
  },
  "procurement:reduce": {
    label: "Reduce Procurement",
    icon: TrendingDown,
    color: "text-amber-600",
    why: "Asset-real economy decoupling — prices likely to correct. Defer non-critical spend.",
    cta: "Adjust open POs",
    to: "/automated-po",
  },
  "procurement:aggressive_buy": {
    label: "Aggressive Buying",
    icon: DollarSign,
    color: "text-emerald-700",
    why: "Counter-cyclical window. Suppliers have idle capacity and will trade volume for price.",
    cta: "Build forward orders",
    to: "/rfq-generation",
  },

  // Inventory actions
  "inventory:maintain": {
    label: "Maintain Inventory",
    icon: Package,
    color: "text-blue-600",
    why: "No regime stress detected — keep working capital where it is.",
    cta: "View inventory",
    to: "/inventory",
  },
  "inventory:build": {
    label: "Build Inventory",
    icon: TrendingUp,
    color: "text-emerald-600",
    why: "Lead-time risk is rising. Add coverage on critical BOM lines before stockouts hit production.",
    cta: "Tune safety stock",
    to: "/inventory-optimization",
  },
  "inventory:drawdown": {
    label: "Draw Down Stock",
    icon: TrendingDown,
    color: "text-amber-600",
    why: "Carrying cost outweighs replenishment risk in this regime — convert stock to cash.",
    cta: "Plan drawdown",
    to: "/inventory",
  },
  "inventory:maximize": {
    label: "Maximize Inventory",
    icon: Maximize2,
    color: "text-emerald-700",
    why: "Cyclical low in input prices. Pre-buying now beats spot pricing for the next 6–12 months.",
    cta: "Increase coverage",
    to: "/inventory-optimization",
  },

  // Production actions
  "production:normal": {
    label: "Maintain Production",
    icon: Activity,
    color: "text-blue-600",
    why: "Demand signal is steady — hold the current schedule.",
    cta: "Open shop floor",
    to: "/operations",
  },
  "production:increase": {
    label: "Increase Production",
    icon: TrendingUp,
    color: "text-emerald-600",
    why: "Forecasted demand is climbing faster than current run rate.",
    cta: "Run allocation",
    to: "/allocation",
  },
  "production:decrease": {
    label: "Scale Back Production",
    icon: TrendingDown,
    color: "text-amber-600",
    why: "Demand signal is softening; running at rate ties up working capital in finished goods.",
    cta: "Adjust schedule",
    to: "/allocation",
  },
  "production:maximize": {
    label: "Maximize Production",
    icon: Maximize2,
    color: "text-emerald-700",
    why: "Counter-cyclical opportunity — capture margin while inputs are cheap.",
    cta: "Run allocation",
    to: "/allocation",
  },
};

const fallbackUx = (signal: Signal): SignalUx => ({
  label: `${signal.type}: ${signal.action.replace(/_/g, " ")}`.toUpperCase(),
  icon: AlertTriangle,
  color: "text-muted-foreground",
  why: "Signal generated by the regime engine. Open the relevant area to see scoped detail.",
  cta: "Open",
  to:
    signal.type === "inventory"
      ? "/inventory"
      : signal.type === "production"
        ? "/operations"
        : "/procurement",
});

// Procurement actions have the highest dollar leverage — surface them first.
const typePriority: Record<string, number> = {
  procurement: 0,
  inventory: 1,
  production: 2,
};

export function PolicySignals({ signals }: PolicySignalsProps) {
  const [, setLocation] = useLocation();

  if (!Array.isArray(signals) || signals.length === 0) {
    return (
      <Card className="p-6" data-testid="card-policy-signals">
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="font-semibold text-lg">Recommended Actions</h3>
            <Badge variant="secondary" data-testid="badge-signal-count">0</Badge>
          </div>
          <p className="text-sm text-muted-foreground">
            No regime-driven actions right now. Conditions are stable — keep standard
            procurement pace and revisit when the regime shifts.
          </p>
        </div>
      </Card>
    );
  }

  const ranked = [...signals]
    .filter((s) => s?.action && s?.description && s?.type)
    .sort((a, b) => (typePriority[a.type] ?? 9) - (typePriority[b.type] ?? 9));

  return (
    <Card className="p-6" data-testid="card-policy-signals">
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="font-semibold text-lg">Recommended Actions</h3>
            <p className="text-xs text-muted-foreground mt-0.5">
              Each action is tied to the current FDR regime and routes to the page
              where you can execute it.
            </p>
          </div>
          <Badge variant="secondary" data-testid="badge-signal-count">
            {ranked.length}
          </Badge>
        </div>

        <div className="space-y-3">
          {ranked.map((signal, idx) => {
            const compositeKey = `${signal.type}:${signal.action}`;
            const ux = signalConfig[compositeKey] || fallbackUx(signal);
            const Icon = ux.icon;

            return (
              <div
                key={`${compositeKey}-${idx}`}
                className="p-3 rounded-md border bg-card/50 hover-elevate"
                data-testid={`signal-${signal.action}`}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-start gap-3 flex-1 min-w-0">
                    <div className={`mt-0.5 ${ux.color}`}>
                      <Icon className="h-5 w-5" />
                    </div>
                    <div className="flex-1 space-y-1 min-w-0">
                      <div className="font-medium text-sm">{ux.label}</div>
                      <p className="text-xs text-muted-foreground leading-relaxed">
                        {signal.description}
                      </p>
                      <p className="text-xs text-muted-foreground/80 leading-relaxed pt-1">
                        <span className="font-medium text-foreground/70">
                          Why:
                        </span>{" "}
                        {ux.why}
                      </p>
                    </div>
                  </div>
                  <Badge
                    variant="outline"
                    className="text-xs whitespace-nowrap capitalize"
                  >
                    {signal.type}
                  </Badge>
                </div>
                <div className="mt-3 flex justify-end">
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-7 text-xs gap-1"
                    onClick={() => setLocation(ux.to)}
                    data-testid={`signal-action-${signal.action}`}
                  >
                    {ux.cta}
                    <ArrowRight className="h-3 w-3" />
                  </Button>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </Card>
  );
}
